vich_uploader:
    db_driver: orm

    mappings:
        category:
            uri_prefix: '%app.path.category_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.category_images%'
